### ISSUE TITLE
Can I use this as as dokku (not dokku-alt) plugin?

### ISSUE THREAD

**Issue by dmr** [yabawock/dokku-alt-postgresql#1]
I heard that dokku-alt is considered old nowadays so we are think about switching to dokku --> Are there any special adjustments why this plugin is dokku-alt and can we continue to use in dokku?

Thanks,
Daniel

**Comment by yabawock** [comment]
This is not a dokku / dokku-alt plugin. This is only a Dockerfile for creating an alternative PostgreSQL image. It's not really specific to either one of dokku-alt or dokku, but the plugin connecting dokku and this image need to work similarly to the plugin included with dokku-alt. I haven't looked at the many different implementations available for dokku in a while and couldn't say if any one of them would work out of the box.

**Comment by dmr** [comment]
Thank you for the explanation.
I'll look into one of the established plugins instead.
